name: Deploy

on:
  push:
    paths-ignore:
      - 'docs/**'
      - '**/README.md'
      - 'media'
    branches:
      - main

jobs:
  deploy-website:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
          cache: 'yarn'
      - uses: jwlawson/actions-setup-cmake@v1.12
        with:
          cmake-version: '3.23.0'
      - uses: mymindstorm/setup-emsdk@v11
        with:
          version: '3.1.8'
          actions-cache-folder: 'emsdk-cache'
      - uses: seanmiddleditch/gha-setup-ninja@master
        with:
          version: '1.10.2'
      - name: Install
        run: yarn install --immutable --inline-builds
      - name: Build
        run: yarn run build
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3.6.1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
